[package]
name = "mnist-wasm"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.33.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.121"
wasm-bindgen = "0.2.92"

[lib]
crate-type = ["cdylib", "rlib"]
